plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/workspace/ac285a27-dc43-43b0-8c53-74f90de3864f/sessions/agent_4e9c8ae2-92d0-469d-829c-da66cebece54/satisfactory-planner/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]